# Generated by Django 3.0.2 on 2020-02-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.City')),
            ],
        ),
        migrations.CreateModel(
            name='Restro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('rating', models.CharField(choices=[(3.2, 3.2), (3.5, 3.5), (3.7, 3.7), (3.8, 3.8), (4.2, 4.2), (4.4, 4.4), (4.6, 4.6), (4.8, 4.8), (4.9, 4.9)], max_length=20)),
                ('discount', models.CharField(choices=[(30, '30%'), (40, '40%'), (50, '50%'), (60, '60%')], max_length=20)),
                ('price_for_two', models.IntegerField()),
                ('pic', models.ImageField(upload_to='restro_img')),
                ('type', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg'), ('both', 'both')], max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Location')),
            ],
        ),
    ]
