# Generated by Django 3.0.2 on 2020-02-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restro',
            name='discount',
            field=models.IntegerField(choices=[(30, '30%'), (40, '40%'), (50, '50%'), (60, '60%')]),
        ),
        migrations.AlterField(
            model_name='restro',
            name='rating',
            field=models.FloatField(choices=[(3.2, 3.2), (3.5, 3.5), (3.7, 3.7), (3.8, 3.8), (4.2, 4.2), (4.4, 4.4), (4.6, 4.6), (4.8, 4.8), (4.9, 4.9)]),
        ),
    ]
