# Generated by Django 3.0.2 on 2020-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_auto_20200212_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restro',
            name='pic',
            field=models.ImageField(upload_to='media/restro_img'),
        ),
    ]
