# Generated by Django 3.0.2 on 2020-02-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_auto_20200212_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestroItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, choices=[('Best Seller', 'Best Seller'), ('Must Try', 'Must Try')], max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='media/restro_item_img')),
                ('category', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('restro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Restro')),
            ],
        ),
    ]
