# Generated by Django 3.0.2 on 2020-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_restroitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restroitem',
            name='count',
        ),
        migrations.AlterField(
            model_name='restroitem',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
