# Generated by Django 3.0.2 on 2020-03-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_json',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.RestroItem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='foodie.OrderItem'),
            preserve_default=False,
        ),
    ]
