# Generated by Django 3.0.2 on 2020-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_auto_20200304_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
