# Generated by Django 3.0.2 on 2020-03-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0016_auto_20200307_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
