# Generated by Django 3.0.2 on 2020-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0020_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('Order Confirmed', 'Order Confirmed'), ('Order Cancelled', 'Order Cancelled'), ('Order Being Prepared', 'Order Being Prepared'), ('Order Pickup', 'Order Pickup'), ('Order Deliverd', 'Order Deliverd')], max_length=100, null=True),
        ),
    ]
