# Generated by Django 3.0.2 on 2020-03-12 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0022_auto_20200311_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
