# Generated by Django 3.0.2 on 2020-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0024_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroitem',
            name='type',
            field=models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='veg', max_length=10),
        ),
    ]
