# Generated by Django 3.0.2 on 2020-03-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Favourite'),
            preserve_default=False,
        ),
    ]
