# Generated by Django 3.0.2 on 2020-03-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
