# Generated by Django 3.0.2 on 2020-03-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='flat_no',
        ),
    ]
