# Generated by Django 3.0.2 on 2020-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_address_flat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=50),
        ),
    ]
