# Generated by Django 3.0.2 on 2020-03-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restroadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreceived',
            name='restro',
        ),
        migrations.AddField(
            model_name='orderreceived',
            name='restro_profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='restroadmin.RestroProfile'),
            preserve_default=False,
        ),
    ]
